### PR TITLE
Intersection2

### PR DESCRIPTION
**Pull request by jlaura**

### CODE REVIEW

**Comment by jlaura** [comment]
Tests were run with:

- temperature dependent focal length that matches ISIS3
- Hard coded camera position that matches ISIS3 to the prevision of the qview application (even with identical kernels, the positioning information does not match the ISD generator - no idea why).  Tested all LT aberration options.
- distortion model

The distortion model test is still failing locally for me.  This with the correct ISD loaded.  @twilson271828 can you check out the distortion model test?

Results:

```bash
[ RUN      ] MdisNacSensorModelTest.imageToGroundCenter
/data/camera_model/tests/MdisNacSensorModelTest.cpp:41: Failure
      Expected: truth[0]
      Which is: 1.12925e+06
To be equal to: xyz.x
      Which is: 1.12926e+06
/data/camera_model/tests/MdisNacSensorModelTest.cpp:42: Failure
      Expected: truth[1]
      Which is: -1.59926e+06
To be equal to: xyz.y
      Which is: -1.59925e+06
/data/camera_model/tests/MdisNacSensorModelTest.cpp:43: Failure
      Expected: truth[2]
      Which is: 1.45528e+06
To be equal to: xyz.z
      Which is: 1.45529e+06
```

```bash
[ RUN      ] MdisNacSensorModelTest.imageToGroundOffCenter
/data/camera_model/tests/MdisNacSensorModelTest.cpp:55: Failure
      Expected: truth[0]
      Which is: 1.11595e+06
To be equal to: xyz.x
      Which is: 1.11597e+06
/data/camera_model/tests/MdisNacSensorModelTest.cpp:56: Failure
      Expected: truth[1]
      Which is: -1.60344e+06
To be equal to: xyz.y
      Which is: -1.60341e+06
/data/camera_model/tests/MdisNacSensorModelTest.cpp:57: Failure
      Expected: truth[2]
      Which is: 1.46093e+06
To be equal to: xyz.z
      Which is: 1.46094e+06
```

```bash
[ RUN      ] MdisNacSensorModelTest.groundToImage1
/data/camera_model/tests/MdisNacSensorModelTest.cpp:72: Failure
The difference between 512.5 and pt.line is 0.28223466094368632, which exceeds 0.1, where
512.5 evaluates to 512.5,
pt.line evaluates to 512.21776533905631, and
0.1 evaluates to 0.10000000000000001.
/data/camera_model/tests/MdisNacSensorModelTest.cpp:73: Failure
The difference between 512.5 and pt.samp is 0.61048837944588286, which exceeds 0.1, where
512.5 evaluates to 512.5,
pt.samp evaluates to 513.11048837944588, and
0.1 evaluates to 0.10000000000000001.
```

**Comment by jlaura** [comment]
@all We should talk about the sources of errors here.  I will not make the standup today, but perhaps we can touch base sometime between 1 and 3PM?

**Comment by jlaura** [comment]
One thought - we are not correcting at all for curvature.  (Mikhail p. 111)

**Comment by jlaura** [comment]
@all this should be ready to go now.  It might need to be updated to incorporate any changes that @ihumphrey-usgs has made to the itrans usage (for WAC).

**Comment by ihumphrey-usgs** [comment]
:+1: I'll go ahead and merge these changes, I can make the tweaks for WAC in a separate PR.

**Pull request merged**
