### PR TITLE
WAC support, ISD_WAC notebook correctly gets SPICE.

### PR DESCRIPTION
**Pull request by ihumphrey-usgs**
Changes:
- [x] New ISD_WAC notebook gets spacecraft position that matches ISIS.
- [x] MdisNacSensorModel updated with small fixes.
- [x] IsdReader uses 15 precision for reading now.
- [x] New WAC cub, json, tests.

### CODE REVIEW

**Comment by jlaura** [comment]
@ihumphrey-usgs  Can you merge the ISD changes and then I'll get these changes merged in?

**Comment by ihumphrey-usgs** [comment]
@jlaura merged in "theirs" (conflict turned out to be just an execution count)

**Comment by jlaura** [comment]
:+1: :smile_cat: 

Obligatory cat added.

**Comment by ihumphrey-usgs** [comment]
:cactus: :cat2: :100:

**Pull request merged**
